### PR TITLE
set plane coordinates

### PR DESCRIPTION
**Pull request by jburel**
This PR fixes an issue when setting the plane associated to a given shape.
The current implementation does not handle images with for example ``t=1``, ``z=1`` and ``c>1``.
This is based on https://github.com/ome/omero-insight/blob/master/src/main/java/org/openmicroscopy/shoola/util/roi/io/ROIReader.java#L227

### CODE REVIEW

**Comment by ppouchin** [comment]
Ok. It fails because in some tests, ROIs exist without images.
Maybe the "position -> C / Z / T" conversion would make sense when actually [saving](https://github.com/GReD-Clermont/simple-omero-client/blob/main/src/main/java/fr/igred/omero/repository/ImageWrapper.java#L443) the ROI to an image?

**Comment by jburel** [comment]
If the image is accessible from the roi it will work
``roi.getImage()`` will not be ``null`` and it will allow to perform the check

**Comment by ppouchin** [comment]
I have a proposition (currently running test locally):
```java
    protected void copyFromIJRoi(ij.gui.Roi ijRoi) {
        LengthI size          = new LengthI(ijRoi.getStrokeWidth(), UnitsLength.POINT);
        Color   defaultStroke = Optional.ofNullable(Roi.getColor()).orElse(Color.YELLOW);
        Color   defaultFill   = Optional.ofNullable(Roi.getDefaultFillColor()).orElse(TRANSPARENT);
        Color   stroke        = Optional.ofNullable(ijRoi.getStrokeColor()).orElse(defaultStroke);
        Color   fill          = Optional.ofNullable(ijRoi.getFillColor()).orElse(defaultFill);
        data.getShapeSettings().setStrokeWidth(size);
        data.getShapeSettings().setStroke(stroke);
        data.getShapeSettings().setFill(fill);
        // Set the plane 
        int pos = ijRoi.getPosition();
        int c = ijRoi.getCPosition();
        int z = ijRoi.getZPosition();
        int t = ijRoi.getTPosition();
        ij.ImagePlus ip = ij.WindowManager.getImage(ijRoi.getImageID()); //ijRoi.getImage() returns null
        if (ip != null) {
            int stackSize = ip.getStackSize();
            int imageC    = ip.getNChannels();
            int imageT    = ip.getNFrames();
            int imageZ    = ip.getNSlices();
            if (stackSize == imageZ) {
                z = pos;
                //reset values
                c = 1;
                t = 1;
            } else if (stackSize == imageC) {
                c = pos;
                //reset values
                z = 1;
                t = 1;
            } else if (stackSize == imageT) {
                t = pos;
                //reset values
                c = 1;
                z = 1;
            }
        }
        data.setC(Math.max(-1, c - 1));
        data.setZ(Math.max(-1, z - 1));
        data.setT(Math.max(-1, t - 1));
    }
```

**Comment by jburel** [comment]
Feel free to close the PR if your suggestion works or adjust my commits

**Comment by ppouchin** [comment]
Ok. I need to check in ImageJ if it works to be sure, but the tests pass.

**Comment by jburel** [comment]
@ppouchin I will do test with the workflow I have in place already later on

**Comment by jburel** [comment]
With the latest commit using the workflow displaying, the problem is no longer used

**Pull request merged**
