### PR TITLE
Parents of image

### PR DESCRIPTION
**Pull request by Rdornier**
Hello, 

In the continuity of our work on retrieving projects and datasets from an image, I write some methods to get an esay access to wells/plates/screens from a given image.

What do you think ?
Thanks,

Rémy.

ping @romainGuiet, @lacan, @NicoKiaru

### CODE REVIEW

**Comment by ppouchin** [comment]
Sorry, I've been a bit busy with other projects recently. I'll take care of this next week.

**Review by ppouchin — APPROVED** [review]

**Comment by ppouchin** [comment]
Ok. I got delayed by COVID, but I integrated this in the branch for the next release.

**Comment by Rdornier** [comment]
Thank you for merging the branch ! Don't worry for the delay, it wasn't very urgent.
I hope you have recovered well ! 

Best,
Rémy.

**Comment by Rdornier** [comment]
Hello Pierre, 

Do you have an idea of when approximately the 5.9.2 release of simple-omero-client will be available ?
One of our user will need to get plate information from her images.

Thanks,
Rémy.

**Comment by ppouchin** [comment]
Hello, 

Sorry, I could not validate everything I wanted before I left for holidays (and I'm still not back).
I [added a new class to try and check if library components are available](https://github.com/GReD-Clermont/simple-omero-client/pull/37/commits/5cabe8cef2062fdd0990804aeb97868cd040ded7), but I failed to write exhaustive tests.
Also, I was not sure if the class/methods names were appropriate or not.

I opened a PR (#37) if you want to have a look. It mostly tries to solve opened issues and contains small fixes (as well as Javadoc corrections). For example, I changed the behavior for "disconnect": now, if `disconnect()` is called from a sudo client, it will replace the Gateway with an empty instance.

If you think this PR is ok, I can merge it by tomorrow and do the release.

**Comment by Rdornier** [comment]
Hello,

Thanks for answering me during your holidays !
I tested your branch 5_9_2 on some basic scripts and it works well.
From my side, I would say that your PR is ok but I wouldn't want to rush you to do the release if you think what you've not added yet should be released on the 5_9_2.

Of course, the earlier we have the release, the better it is but I prefer to wait a bit for a working homogenous release than having it now but with missing elements.

Thanks again, and enjoy your holdidays
Rémy.

**Pull request merged**
